/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as kip13InterfacesSupportedSol from "./KIP13InterfacesSupported.sol";
export type { kip13InterfacesSupportedSol };
