/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC1155Receiver } from "./IERC1155Receiver";
export type { IKIP37 } from "./IKIP37";
export type { IKIP37MetadataURI } from "./IKIP37MetadataURI";
export type { IKIP37Receiver } from "./IKIP37Receiver";
export type { KIP37 } from "./KIP37";
export type { KIP37Burnable } from "./KIP37Burnable";
export type { KIP37Holder } from "./KIP37Holder";
export type { KIP37Mintable } from "./KIP37Mintable";
export type { KIP37Pausable } from "./KIP37Pausable";
export type { KIP37Receiver } from "./KIP37Receiver";
export type { KIP37Token } from "./KIP37Token";
