/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { KIP13InterfacesSupported } from "./KIP13InterfacesSupported";
export type { SupportsInterfaceWithLookupMock } from "./SupportsInterfaceWithLookupMock";
