/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as kip13 from "./KIP13";
export type { kip13 };
export type { ERC1155ReceiverMock } from "./ERC1155ReceiverMock";
export type { ERC721ReceiverMock } from "./ERC721ReceiverMock";
export type { KIP13CheckerMock } from "./KIP13CheckerMock";
export type { KIP13Mock } from "./KIP13Mock";
export type { KIP17FullMock } from "./KIP17FullMock";
export type { KIP17MintableBurnableImpl } from "./KIP17MintableBurnableImpl";
export type { KIP17Mock } from "./KIP17Mock";
export type { KIP17PausableMock } from "./KIP17PausableMock";
export type { KIP17ReceiverMock } from "./KIP17ReceiverMock";
export type { KIP37BurnableMock } from "./KIP37BurnableMock";
export type { KIP37Mock } from "./KIP37Mock";
export type { KIP37PausableMock } from "./KIP37PausableMock";
export type { KIP37ReceiverMock } from "./KIP37ReceiverMock";
export type { KIP37TokenMock } from "./KIP37TokenMock";
export type { KIP7BurnableMock } from "./KIP7BurnableMock";
export type { KIP7MetadataMock } from "./KIP7MetadataMock";
export type { KIP7MintableMock } from "./KIP7MintableMock";
export type { KIP7Mock } from "./KIP7Mock";
export type { KIP7PausableMock } from "./KIP7PausableMock";
export type { MinterRoleMock } from "./MinterRoleMock";
export type { PauserRoleMock } from "./PauserRoleMock";
